## Question 1

## Problem 1

In [31]:
L = [1,2,3,4,5,6,7,8,9]
print(L)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [32]:
print (min(L), max(L), (min(L)+ max(L))/2)

1 9 5.0


In [33]:
def my_function(L):
    return ((min(L)), (max(L)), (((min(L)) + (max(L)))/2))

In [34]:
print (my_function(L))

(1, 9, 5.0)


## Problem 2

In [35]:
# integers

int_1 = 1
int_2 = int_1
int_2 = 3
int_1 == int_2

False

## so integers are immutable

In [36]:
# strings

str_1 = 'Leili'
str_2 = str_1
str_2 = 'Narges'
str_1 == str_2

False

## so strings are immutable

In [37]:
# lists

list_1 = [1, 3, 4, 5]
list_2 = list_1
list_2[1] = 8
list_1 == list_2

True

## so lists ar mutable

In [38]:
# tuples

dum = (123, 456, 'a')
dee = (123, 456, 'a')
dum is dee

False

## so tuples are immutable

In [39]:
# sets

x = set([1, 2, 3])
y = x
y |= set([4, 5, 6])
print(x)
print(y)

{1, 2, 3, 4, 5, 6}
{1, 2, 3, 4, 5, 6}


## so sets are mutable

## Problem 3

In [40]:
import calculator as leili

In [41]:
run calculator

In [42]:
def hulu(G, E):
    return sqrt(leili.plus(leili.multiply(G, G), leili.multiply(E, E)))

In [43]:
hulu(2,4)

4.47213595499958

## Question 2

## Problem 1

In [44]:
import numpy as np

def matrix():
    A = np.array([[3, -1, 4],[1, 5, -9]])
    B = np.array([[2, 6, -5, 3],[5, -8, 9, 7],[9, -3, -2, -3]])
    return(A @ B)

In [45]:
matrix()

array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

## Problem 2

In [46]:
def matrix():
    A = np.array([[3, 1, 4],[1, 5, 9],[-5, 3, 1]])
    return((-A @ -A @ -A) + 9 * (A @ A) - 15 * (A))

In [47]:
matrix()

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## Problem 5

In [48]:
def matrix_1():
    A = np.array([[0, 2, 4],[1, 3, 5]])
    B = np.array([[3, 0, 0],[3, 3, 0],[3, 3, 3]])
    C = np.array([[-2, 0, 0],[0, -2, 0],[0, 0, -2]])
    
    raw1 = np.column_stack((np.zeros((3,3)), A.T, np.eye(3)))
    raw2 = np.column_stack((A, np.zeros((2, 2)), np.zeros_like(A)))
    raw3 = np.column_stack((B, np.zeros_like(A.T), C))
    newmatrix = np.concatenate((raw1, raw2, raw3))
            
    return newmatrix

In [49]:
matrix_1()

array([[ 0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  2.,  3.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  4.,  5.,  0.,  0.,  1.],
       [ 0.,  2.,  4.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  3.,  5.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0., -2.,  0.,  0.],
       [ 3.,  3.,  0.,  0.,  0.,  0., -2.,  0.],
       [ 3.,  3.,  3.,  0.,  0.,  0.,  0., -2.]])

## Question 3

## Problem 1

In [2]:
class Backpack(object):
    def __init__(self, name, color, max_size = 5):
        self.name = name
        self.color = color
        self.max_size = max_size
        self.contents = []
        
    def put(self, item):
        
        if len(self.contents) >= self.max_size:
            print("no room!")
        if len(self.contents) < self.max_size:
            self.contents.append(item)
                
    def dump(self):
        self.contents = []

In [3]:
testpack = Backpack("leili", "Narges")
for item in ["pen", "notebook", "board", "pc", "chair", "table", "desk"]:
    testpack.put(item)
    print(testpack.contents)

['pen']
['pen', 'notebook']
['pen', 'notebook', 'board']
['pen', 'notebook', 'board', 'pc']
['pen', 'notebook', 'board', 'pc', 'chair']
no room!
['pen', 'notebook', 'board', 'pc', 'chair']
no room!
['pen', 'notebook', 'board', 'pc', 'chair']


In [10]:
testpack.dump()

## problem 2

In [4]:
class Jetpack(Backpack):
    
    def __init__(self, name, color, max_size = 2, fuel = 10):
        
        Backpack.__init__(self, name, color, max_size)
        self.fuel = fuel
    
    def fly(self, burnamnt):
        
        if burnamnt > fuel:
            print("Not enough fuel!")
            
        else:
            fuel = fuel - burnamnt
        
    def dump(self):
        
        self.contents = []
        self.fuel = 0

In [5]:
test_Jetpack = Jetpack("leili", "narges")

test_Jetpack.put("picture")
print(test_Jetpack.contents)

['picture']


In [6]:
print(test_Jetpack.fuel)

10


In [8]:
test_Jetpack.dump()
print(test_Jetpack.contents)

[]


In [9]:
print(test_Jetpack.fuel)

0
